name: Jay Blogs
title: Jay Blogs
description: Jay Blogs is where I write my thoughts growing up as a software developer plus rants about sociatal issues.
tags:
  - blog
  - jekyll
  - netlify
  - philippines
  - software-developer
show_hero: true
menu:
  - title: Home
    url: /
  - title: Adriane James
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: adrianejames27@gmail.com
# See: https://disqus.com/
disqus_username: jay27_22
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
